export const SET_TODOS = 'SET_TODOS'
export const ADD = 'ADD'
export const DELETE = 'DELETE'
export const COMPLETE = 'COMPLETE'
export const SET_ACTIVE_FILTER = 'SET_ACTIVE_FILTER'
export const EDIT = 'EDIT'